### ISSUE TITLE
After the order was executed, nothing happened

### ISSUE THREAD

**Issue by hanyaqian** [amake/TMX2Corpus#2]
Hi @amake 

After the following command was executed, nothing happened, why?
(tmx2corpus <path to TMX file>)

thanks :)

**Comment by amake** [comment]
Did you install the package? If you did, you should get the following output:

```sh
% tmx2corpus 
usage: tmx2corpus [-h] [--verbose] path [path ...]
tmx2corpus: error: too few arguments
```
